### ISSUE TITLE
Convert check for CSR acceptance to script instead of a loop of tasks

### ISSUE THREAD

**Issue by jaredhocutt** [jaredhocutt/openshift4-deploy#44]
During the OpenShift install, the check for worker nodes becoming ready is done with a set of tasks that gets called over and over until all worker nodes show ready. It works well, but is pretty ugly and leads to confusion when watching the playbook output.

Convert the following to a bash script that executes from the bastion:

```yaml
- name: Check worker nodes status
  command: >-
    oc get nodes
    --selector='node-role.kubernetes.io/worker='
    --output=custom-columns='READY:status.conditions[?(@.type=="Ready")].status'
    --no-headers
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  retries: 10
  delay: 5
  until: r_check_worker_nodes_status.rc == 0
  changed_when: no
  register: r_check_worker_nodes_status

- set_fact:
    number_of_ready_workers: "{{ r_check_worker_nodes_status.stdout | regex_findall('True') | length }}"

# https://docs.openshift.com/container-platform/latest/installing/installing_bare_metal/installing-bare-metal.html#installation-approve-csrs_installing-bare-metal
- name: Approve any outstanding CSRs
  script: "{{ role_path }}/files/csr_approve.sh"
  environment:
    KUBECONFIG: "{{ openshift_install_dir }}/auth/kubeconfig"
  failed_when: no
  when: number_of_ready_workers != '3'

- name: Set all worker nodes ready status
  set_fact:
    p_all_worker_nodes_ready: yes
  when: number_of_ready_workers == '3'

- block:
    - name: Wait before checking again
      pause:
        seconds: 10

    - include_tasks: wait_for_worker_nodes.yml
  when: not p_all_worker_nodes_ready
```
